import { Roboto } from 'next/font/google'
import "./globals.css";
import { ReduxProvider } from '@/redux/ReduxProvider';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={roboto.className}>
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
